name: build_pro
description: "Civil Project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  get_storage: ^2.1.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  sensors_plus: ^5.0.1
  geolocator: ^11.0.0
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^32.2.9
  printing: ^5.14.2
  image_gallery_saver: ^2.0.3
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# MUST BE TOP-LEVEL (NOT INDENTED)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#F8FAFC" # Matches your Soft White background
    theme_color: "#1E3A8A"      # Matches your Deep Blue primary
    
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
    
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  # Ensure your icon path is included in assets
  assets:
    - assets/icon/