// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-qQCWig8ApMRI3L99hKxQCcKtSXC2DI',
    appId: '1:633971681989:web:156132a63b1c256d925eac',
    messagingSenderId: '633971681989',
    projectId: 'civilengg',
    authDomain: 'civilengg.firebaseapp.com',
    storageBucket: 'civilengg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRPEw9kUV343pSyJk8S-NsfuX3M4U0wY',
    appId: '1:633971681989:android:46b3088c4831da62925eac',
    messagingSenderId: '633971681989',
    projectId: 'civilengg',
    storageBucket: 'civilengg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNHz3tiZyD0Oa7aS24wtYqbuNdmZhVCQ',
    appId: '1:633971681989:ios:333ff7f0d4433065925eac',
    messagingSenderId: '633971681989',
    projectId: 'civilengg',
    storageBucket: 'civilengg.firebasestorage.app',
    iosBundleId: 'com.civil.engg.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaNHz3tiZyD0Oa7aS24wtYqbuNdmZhVCQ',
    appId: '1:633971681989:ios:333ff7f0d4433065925eac',
    messagingSenderId: '633971681989',
    projectId: 'civilengg',
    storageBucket: 'civilengg.firebasestorage.app',
    iosBundleId: 'com.civil.engg.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-qQCWig8ApMRI3L99hKxQCcKtSXC2DI',
    appId: '1:633971681989:web:08902608afdb54a0925eac',
    messagingSenderId: '633971681989',
    projectId: 'civilengg',
    authDomain: 'civilengg.firebaseapp.com',
    storageBucket: 'civilengg.firebasestorage.app',
  );

}